{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "1",
            "properties": {
                "ward": "48",
                "grantees": "FIRSTRUST BANK",
                "grantors": "DESIMONE JAMES",
                "objectid": 1,
                "unit_num": None,
                "zip_code": "191452825",
                "record_id": "180",
                "condo_name": None,
                "reg_map_id": None,
                "address_low": 1928,
                "discrepancy": None,
                "document_id": 18,
                "receipt_num": None,
                "street_name": "LAMBERT",
                "address_high": None,
                "display_date": "2024-06-26T18:22:03+00:00",
                "receipt_date": "2024-06-26T17:43:48+00:00",
                "document_date": None,
                "document_type": "MORTGAGE",
                "legal_remarks": None,
                "street_predir": "S",
                "street_suffix": "ST",
                "assessed_value": None,
                "matched_regmap": "015S140282",
                "property_count": 1,
                "recording_date": "2024-06-26T18:22:03+00:00",
                "street_address": "1928 S LAMBERT ST",
                "street_postdir": None,
                "opa_account_num": "481352600",
                "address_low_frac": None,
                "local_tax_amount": None,
                "state_tax_amount": None,
                "fair_market_value": None,
                "local_tax_percent": None,
                "state_tax_percent": None,
                "address_low_suffix": None,
                "cash_consideration": 0,
                "common_level_ratio": None,
                "other_consideration": None,
                "total_consideration": 0,
                "adjusted_assessed_value": None,
                "adjusted_local_tax_amount": None,
                "adjusted_state_tax_amount": None,
                "adjusted_fair_market_value": None,
                "adjusted_cash_consideration": 0,
                "adjusted_other_consideration": None,
                "adjusted_total_consideration": 0,
            },
            "geometry": {"type": "Point", "coordinates": [-75.180289817, 39.927585403]},
        }
    ],
}
