name: test-pr

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: testing_environment
  cancel-in-progress: false

jobs:
  api_catalog:
    name: API Catalog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Copy private databridge-schemas repo for use in the container (just so pytests work, in prod it will get the gh repo from a sidecar)
      - name: Checkout Databridge Schemas
        uses: actions/checkout@v4
        with:
          repository: CityOfPhiladelphia/databridge-schemas
          ssh-key: ${{ secrets.DB_SCHEMAS_DEPLOY_KEY }}
          path: ./databridge-schemas # Places it in the build context
          ref: main

      - name: Move databridge schemas
        run: |
          sudo mkdir -p /scripts
          sudo chown -R runner:docker /scripts
          mv databridge-schemas /scripts/
          ls /scripts

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: UV Pip Install
        run: |
          uv venv
          uv pip install .

      - name: Generate OpenAPI Spec
        run: |
          uv run extract_openapi.py
  build:
    name: build-test
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # This is a github function? Ref doc: https://github.com/actions/checkout#checkout-a-different-branch
      # IMPORTANT NOTE: pinned to v3 instead of master, because v4 uses node20 and glibc 2.27. Amazon linux 2 atm only supports
      # glibc 2.26. Change notes: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # Copy private databridge-schemas repo for use in the container (just so pytests work, in prod it will get the gh repo from a sidecar)
      - name: Checkout Databridge Schemas
        uses: actions/checkout@v4
        with:
          repository: CityOfPhiladelphia/databridge-schemas
          ssh-key: ${{ secrets.DB_SCHEMAS_DEPLOY_KEY }}
          path: ./databridge-schemas # Places it in the build context
          ref: main

      # Build our docker container and insert our AWS secret keys
      # no-cache so we're sure we're getting all changes (such as geopetl changes)
      # NOTE: right now just build and test python 3.12 for prod deployment, but we have 3.11 and 3.13 Dockerfiles too.
      - name: Build docker container
        run: docker build -t databridge_api_dev:dev --no-cache .

      - name: pytests
        run: >
          docker run --rm
          -e CARTO_TOKEN
          -e AGO_USER
          -e AGO_PASSWORD
          -e AGO_URL
          databridge_api_dev:dev
          pytest
          --maxfail=4
          --tb=short
          -v
        env:
          CARTO_TOKEN: ${{ secrets.CARTO_TOKEN }}
          AGO_USER: ${{ secrets.AGO_USER }}
          AGO_PASSWORD: ${{ secrets.AGO_PASSWORD }}
          AGO_URL: ${{ secrets.AGO_URL }}

      # https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Docker Push to dev ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
        run: |
          docker tag databridge_api_dev:dev $ECR_REPOSITORY_URL:dev
          docker push $ECR_REPOSITORY_URL:dev
